enum UserActionTypes {
  GET_USERS_START = 'GET_USERS_START',
  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE = 'GET_USERS_FAILURE',

  SAVE_USER_START = 'SAVE_USER_START',
  SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS',
  SAVE_USER_FAILURE = 'SAVE_USER_FAILURE',
}

export default UserActionTypes;
